image: node:14

pages:
  stage: deploy
  script:
    - cp public/index.html public/404.html
    - npm install
    - npm run build
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
